### PR TITLE
Fix #216 Publicly accessible PDF file URL is not yet supported in the input_file content data

### LINKED ISSUE #216: Publicly accessible PDF file URL is not yet supported in the input_file content data
I'm getting the error `Error: 400 Missing required parameter: 'input[0].content[0]'.` when running this code:

```
const agentInput = [
  { role: "user", content: [{ type: "input_file", file: <pdf_dataurl> }] },
];
const runResult = await run(orderingEntrypointAgent, agentInput, { maxTurns: 500 });
```

From what I can tell from the documentation, I have given the input in the required shape but not sure why its erroring. 

Thanks!

### PR DESCRIPTION
**Pull request by seratch**
This pull request resolves #216

### CODE REVIEW

File: examples/basic/remote-pdf.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
+import { Agent, run } from '@openai/agents';
+
+const URL = 'https://www.berkshirehathaway.com/letters/2024ltr.pdf';
```
Comment (seratch) [inline examples/basic/remote-pdf.ts]: This URL is used in the document, so I went with it: https://platform.openai.com/docs/guides/pdf-files?api-mode=responses

File: packages/agents-core/src/types/protocol.ts [hunk 2]
```diff
@@ -91,9 +91,17 @@ export const InputFile = SharedBase.extend({
    */
   file: z
     .string()
+    .describe(
```
Comment (seratch) [inline packages/agents-core/src/types/protocol.ts:94]: developers can pass 1) as string or 2) `{ url: '....' }`

File: packages/agents-openai/src/openaiResponsesModel.ts [hunk 3]
```diff
@@ -525,7 +535,10 @@ function getInputItems(
           type: 'code_interpreter_call',
           id: item.id!,
           code: item.providerData?.code ?? '',
-          results: item.providerData?.results ?? [],
+          // This property used to be results, so keeping both for backward compatibility
```
Comment (seratch) [inline packages/agents-openai/src/openaiResponsesModel.ts]: same change with https://github.com/openai/openai-agents-js/pull/222

**Review by seratch — COMMENTED** [review]
comments for reviewers

File: examples/basic/remote-pdf.ts (hunk 1 above)
Comment (dkundel-openai) [reply examples/basic/remote-pdf.ts]: Can we use small url here? It's a nit pick but URL is a built in class in JS

Comment (seratch) [reply examples/basic/remote-pdf.ts]: thanks, renamed this and the original remote-image.ts as well
