### PR TITLE
fix: #799 Expose raw input and validation error in tool parsing failures

### LINKED ISSUE #799: No access to raw input/validation error in tool error handling
### Please read this first

- **Have you read the docs?** [Agents SDK docs](https://openai.github.io/openai-agents-js/)
> yes
- **Have you searched for related issues?** Others may have faced similar issues.
> yes, related: #723 

### Describe the bug

When an LLM returns invalid JSON or a value that fails Zod validation for a tool call, the `errorFunction` only receives a generic `ModelBehaviorError` with the message `"Invalid JSON input for tool"`.

Without the `errorFunction`, there is no built-in logic inside the agents SDK to retry tool calls, nor attempt self healing.

Given the original validation error and raw input string are discarded, downstream code cannot easily (using `errorFunction`):
- Implement self-healing (e.g., constructing a corrective prompt for the LLM)
- Apply heuristic fixes (e.g., repairing unmatched braces, trailing commas)
- Capture detailed validation failures for debugging/auditing

### Debug information

- Agents SDK version: (e.g. `v0.3.7`)
- Runtime environment (e.g. `Node.js 22.16.0`)

### Repro steps

```
import { tool } from '@openai/agents-core';
import { z } from 'zod';
import { RunContext } from '@openai/agents-core';

const myTool = tool({
  name: 'greet',
  description: 'Greet a user',
  parameters: z.object({
    name: z.string(),
    age: z.number(),
  }),
  execute: async ({ name, age }) => `Hello ${name}, you are ${age}`,
  errorFunction: (context, error) => {
    // Bug: We only get a generic error message
    console.log('Error type:', (error as Error).constructor.name);
    console.log('Error message:', (error as Error).message);

    // These don't exist on the error - no way to implement self-healing
    console.log('Raw input:', (error as any).toolInput); // undefined
    console.log('Original error:', (error as any).originalError); // undefined

    return 'Tool failed';
  },
});

async function main() {
  // Simulate LLM returning invalid JSON (age should be number, not string)
  console.log('--- Test 1: Zod validation failure ---');
  await myTool.invoke(new RunContext(), '{"name": "Alice", "age": "not a number"}');

  console.log('\n--- Test 2: Malformed JSON ---');
  await myTool.invoke(new RunContext(), '{name: Alice}');
}

main();
```

### Expected behavior

The `errorFunction` should receive an error object that includes:
- `toolInput`: The raw input string that failed parsing/validation
- `originalError`: The underlying error (JSON parse error or Zod validation error)

Built in tool call retries would be great, but I think this would be a rather significant change that would alter the way users expect the agent SDK to work.

I've opened a PR with a suggested minimal fix that introduces a new `InvalidToolInputError` class extending `ModelBehaviorError`. This error includes `toolInput`, `originalError`, `runContext`, and `toolCallDetails` properties (the same data/context given to the tool `execute` function), giving downstream code the flexibility to implement better error handling or self-healing logic.

Given this new error extends the original, and does not change ordering/naming of arguments/parameters, it should be a low risk, non-breaking change that does not change how agents work/break expectations of existing codebases.

### PR DESCRIPTION
**Pull request by shrirajh**
This pull request resolves #799 

Introduces a new `InvalidToolInputError` class extending `ModelBehaviorError` that includes:
- `toolInput`: the raw input string that failed parsing/validation
- `originalError`: the underlying JSON parse or Zod validation error
- `runContext` and `toolCallDetails`: same context available to the tool's `execute` function

This gives downstream code the flexibility to implement custom error handling or self-healing logic via `errorFunction`.

### CODE REVIEW

File: packages/agents-core/src/errors.ts [hunk 1]
```diff
@@ -35,6 +37,38 @@ export class MaxTurnsExceededError extends AgentsError {}
...
+  /** The details of the tool call made by the model. */
+  toolCallDetails?: { toolCall: protocol.FunctionCallItem };
+
+  constructor(
+    message: string,
+    state?: RunState<any, Agent<any, any>>,
+    originalError?: unknown,
+    toolInput?: string,
+    runContext?: RunContext<any>,
+    toolCallDetails?: { toolCall: protocol.FunctionCallItem },
```
Comment (seratch) [inline packages/agents-core/src/errors.ts]: Can you group these like `toolInvocation: { runContext, input, details }`?

**Review by seratch — CHANGES_REQUESTED** [review]
Thanks for sending this pull request! Can you adjust three things?

1. as mentioned in my comment, can you move the tool invoke method args into a single object for organizing things?
2. add some unit tests covering the sceanarios
3. use patch version bump in the changeset file

File: .changeset/dry-pets-hug.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@openai/agents-core': minor
```
Comment (seratch) [inline .changeset/dry-pets-hug.md]: This project is still young and use patch for all backward-compatible changes:
```suggestion
'@openai/agents-core': patch
```

**Comment by shrirajh** [comment]
Hey @seratch thank you for your prompt review - I've addressed your 3 comments in separate commits. I wasn't sure whether you prefer a force push w/ rebase or whether you'd squash merge.

File: .changeset/dry-pets-hug.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@openai/agents-core': patch
+---
+
+Expose raw input and validation error in tool parsing failures via new InvalidToolInputError class, enabling self-healing implementations
```
Comment (seratch) [inline .changeset/dry-pets-hug.md]:
```suggestion
fix: #799 Expose raw input and validation error in tool parsing failures
```
