### PR TITLE
fix: #425 improve the compatibility for conversationId / previousResponseId + tool calls

### LINKED ISSUE #425: Agent + tool + conversationId throws invalid request error - Duplicate item found with id rs_xxx. Remove duplicate items from your input and try again.
### Debug information

- Agents SDK version: `v0.1.0`
- Runtime environment: `Node v22.19.0`

### Repro steps
When running the following code from the command line:

```typescript
import { Agent, run, tool } from '@openai/agents';
import { z } from 'zod';

import OpenAI from 'openai';

const getWeatherTool = tool({
    name: 'get_weather',
    description: 'Get the weather for a given city',
    parameters: z.object({ city: z.string() }),
    strict: true,
    async execute({ city }) {
        return `The weather in ${city} is sunny.`;
    },
});

async function main() {
    const client = new OpenAI();
    const conversation = await client.conversations.create({});
    const agent = new Agent({
        name: 'Assistant',
        instructions: 'You are a helpful assistant. be VERY concise.',
        model: "gpt-5",
        tools: [getWeatherTool],
    });
    const runOptions = { conversationId: conversation.id };
    const result = await run(agent, "What is the weather in NYC?", runOptions);
    console.log(`Output: ${result.finalOutput}`);
}
if (require.main === module) {
    main().catch(console.error);
}
```

I am getting this exception:
```
BadRequestError: 400 Duplicate item found with id rs_68b8366ad2848195beb3348e5860cc81029faaa0843e7ce0. Remove duplicate items from your input and try again.
    at APIError.generate (/Users/oren/Documents/dev/opstream/opstream-frontend/packages/functions/node_modules/@openai/agents-openai/node_modules/openai/core/error.js:45:20)
    at OpenAI.makeStatusError (/Users/oren/Documents/dev/opstream/opstream-frontend/packages/functions/node_modules/@openai/agents-openai/node_modules/openai/client.js:163:32)
    at OpenAI.makeRequest (/Users/oren/Documents/dev/opstream/opstream-frontend/packages/functions/node_modules/@openai/agents-openai/node_modules/openai/client.js:308:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async #fetchResponse (/Users/oren/Documents/dev/opstream/opstream-frontend/packages/functions/node_modules/@openai/agents-openai/dist/openaiResponsesModel.js:733:26)
    at async /Users/oren/Documents/dev/opstream/opstream-frontend/packages/functions/node_modules/@openai/agents-openai/dist/openaiResponsesModel.js:752:30
    at async /Users/oren/Documents/dev/opstream/opstream-frontend/packages/functions/node_modules/@openai/agents-core/dist/tracing/createSpans.js:25:24
    at async OpenAIResponsesModel.getResponse (/Users/oren/Documents/dev/opstream/opstream-frontend/packages/functions/node_modules/@openai/agents-openai/dist/openaiResponsesModel.js:751:26)
    at async /Users/oren/Documents/dev/opstream/opstream-frontend/packages/functions/node_modules/@openai/agents-core/dist/run.js:167:51
    at async /Users/oren/Documents/dev/opstream/opstream-frontend/packages/functions/node_modules/@openai/agents-core/dist/tracing/context.js:56:24 {
  status: 400,
  headers: Headers {
    date: 'Wed, 03 Sep 2025 12:37:03 GMT',
    'content-type': 'application/json',
    'content-length': '250',
    connection: 'keep-alive',
    'openai-version': '2020-10-01',
    'openai-organization': 'xxx',
    'openai-project': 'xxx',
    'x-request-id': 'req_a0f9dd423f05226476a6b9b0a2e95386',
    'openai-processing-ms': '721',
    'x-envoy-upstream-service-time': '725',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'cf-cache-status': 'DYNAMIC',
    'set-cookie': 'xxx',
    'x-content-type-options': 'nosniff',
    server: 'cloudflare',
    'cf-ray': '97954bce8d345bd4-LIS',
    'alt-svc': 'h3=":443"; ma=86400'
  },
  requestID: 'req_a0f9dd423f05226476a6b9b0a2e95386',
  error: {
    message: 'Duplicate item found with id rs_68b8366ad2848195beb3348e5860cc81029faaa0843e7ce0. Remove duplicate items from your input and try again.',
    type: 'invalid_request_error',
    param: 'input',
    code: null
  },
  code: null,
  param: 'input',
  type: 'invalid_request_error'
}
```

In the Dashboard traces, it looks like it's coming from the 2nd call to the Model after the tool returns a response:

Image

### Expected behavior

Agent should load the previous inputs from the conversation and log new data to it.

### PR DESCRIPTION
**Pull request by seratch**
This pull request brings https://github.com/openai/openai-agents-python/pull/1827 improvements to TS SDK as well.

Resolves #425

See also: https://github.com/openai/openai-agents-python/issues/1789

### CODE REVIEW

File: packages/agents-core/src/run.ts [hunk 1]
```diff
@@ -178,19 +178,114 @@ export function getTracing(
...
+  }
+
+  return [...originalInput];
+}
+
+/**
+ * Internal module for tracking the items in turns and ensuring that we don't send duplicate items.
+ * This logic is vital for properly handling the items to send during multiple turns
+ * when you use either `conversationId` or `previousResponseId`.
+ * Both scenarios expect an agent loop to send only the new items for each Responses API cal.
```
Comment (seratch) [inline packages/agents-core/src/run.ts]:
```suggestion
 * Both scenarios expect an agent loop to send only new items for each Responses API call.
```

File: packages/agents-core/src/run.ts [hunk 2]
```diff
@@ -178,19 +178,114 @@ export function getTracing(
...
+  // Conversation ID:
+  // - https://platform.openai.com/docs/guides/conversation-state?api-mode=responses#using-the-conversations-api
+  // - https://platform.openai.com/docs/api-reference/conversations/create
+  public conversationId?: string;
+
+  // Previous Response ID:
+  // https://platform.openai.com/docs/guides/conversation-state?api-mode=responses#passing-context-from-the-previous-response
+  public previousResponseId?: string;
+
+  // Using this flag because WeakSet does not provides a way to check its size
```
Comment (seratch) [inline packages/agents-core/src/run.ts]:
```suggestion
  // Using this flag because WeakSet does not provide a way to check its size
```

**Comment by rm-openai** [comment]
@codex review

**Comment by seratch** [comment]
Since this repo has issues with codex review integration right now, I ran /review command locally, and got the following feedback. This is fair, so need to improve the implementation:

  - [P1] Avoid resending prior items when resuming state — packages/agents-core/src/run.ts:352-358 When we resume a run by passing an existing RunState (the documented pattern after handling interruptions/approvals), this newly constructed ServerConversationTracker starts empty. On the very next prepareInput call we therefore resend state._originalInput plus every item already in state._generatedItems before we’ve called trackServerItems. In a server-managed conversation (conversationId or previousResponseId) those items were already sent in the earlier turn, so the resumed request will repeat the previous user message and tool call(s). Concretely, if you run with conversationId, hit a tool approval, approve it, and call runner.run(agent, result.state, { conversationId }), the second invocation will replay the prior tool call back to the API, creating duplicate tool executions / protocol errors. We need to seed the tracker from the existing RunState (or otherwise skip the resend) whenever input is a RunState; without that, approval/resume flows are broken.


Checked Python repo too:

  - Python’s runner never accepts an external RunState object—the public entry points Runner.run / run_streamed only take fresh input values and internally start with generated_items: list[RunItem] = [], so
  _ServerConversationTracker.prepare_input always sees an empty list on the first turn of a resume-free run (src/agents/run.py:502-543, src/agents/run.py:147-167).
  - Each turn immediately calls server_conversation_tracker.track_server_items(...), repopulating the tracker before the next loop iteration (src/agents/run.py:640-641 and, for streaming, src/agents/run.py:1011-1012). Because
  there’s no API surface that seeds the tracker with historical generated_items, the replay scenario you found in the TypeScript SDK can’t occur in the current Python flow.
  - The conversation-id/previous-response-id tests confirm the intended “only send new items” behavior for successive turns within a single invocation (tests/test_agent_runner.py:780-856).

  So the TypeScript regression isn’t applicable to the present Python implementation. If we later expose a resumable state similar to TS, we’ll need to seed _ServerConversationTracker with prior items (or skip replay on the
  first prepare_input), but that feature doesn’t exist yet.

**Comment by Kenth06** [comment]
any update on this fix?

**Comment by coryetzkorn** [comment]
Thanks for the fix 🙌

**Comment by MaximDobrolinsky** [comment]
@seratch 
When the fix going to release?
